#!/bin/sh
#install java
apt-get update
apt-get install openjdk-8-jdk
java -version
find /usr/lib/jvm/java-1.8* | head -n 3
vi ~/.bashrc
#set java home path
JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
export JAVA_HOME
export PATH=$PATH:$JAVA_HOME/bin
#log out and back
echo $JAVA_HOME

#install Jenkins
wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
apt-get update
apt-get install jenkins
apt-get install ant
# Start jenkins service
service jenkins start
# Setup Jenkins to start at boot,
chkconfig jenkins on
